"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

SOUND = ["resources/sound/npc_attack.wav", "resources/sound/npc_death.wav", "resources/sound/npc_pain.wav", "resources/sound/player_pain.wav", "resources/sound/shotgun.wav", "resources/sound/theme.mp3"]
GREEN_LIGHT = ["resources/sprites/animated_sprites/green_light/0.png", "resources/sprites/animated_sprites/green_light/1.png", "resources/sprites/animated_sprites/green_light/2.png", "resources/sprites/animated_sprites/green_light/3.png"]
RED_LIGHT = ["resources/sprites/animated_sprites/red_light/0.png", "resources/sprites/animated_sprites/red_light/1.png", "resources/sprites/animated_sprites/red_light/2.png", "resources/sprites/animated_sprites/red_light/3.png"]

CACO_ATTACK = ["resources/sprites/npc/caco_demon/attack/0.png", "resources/sprites/npc/caco_demon/attack/1.png", "resources/sprites/npc/caco_demon/attack/2.png", "resources/sprites/npc/caco_demon/attack/3.png", "resources/sprites/npc/caco_demon/attack/4.png"]
CACO_DEATH = ["resources/sprites/npc/caco_demon/death/0.png", "resources/sprites/npc/caco_demon/death/1.png", "resources/sprites/npc/caco_demon/death/2.png", "resources/sprites/npc/caco_demon/death/3.png", "resources/sprites/npc/caco_demon/death/4.png", "resources/sprites/npc/caco_demon/death/5.png"]
CACO_IDLE = ["resources/sprites/npc/caco_demon/idle/0.png", "resources/sprites/npc/caco_demon/idle/1.png", "resources/sprites/npc/caco_demon/idle/2.png", "resources/sprites/npc/caco_demon/idle/3.png", "resources/sprites/npc/caco_demon/idle/4.png", "resources/sprites/npc/caco_demon/idle/5.png", "resources/sprites/npc/caco_demon/idle/6.png", "resources/sprites/npc/caco_demon/idle/7.png"]
CACO_PAIN = ["resources/sprites/npc/caco_demon/pain/0.png", "resources/sprites/npc/caco_demon/pain/1.png"]
CACO_WALK = ["resources/sprites/npc/caco_demon/walk/0.png", "resources/sprites/npc/caco_demon/walk/1.png", "resources/sprites/npc/caco_demon/walk/2.png"]
CACO_DEFAULT = ["resources/sprites/npc/caco_demon/0.png"]

CYBER_ATTACK = ["resources/sprites/npc/cyber_demon/attack/0.png", "resources/sprites/npc/cyber_demon/attack/1.png"]
CYBER_DEATH = ["resources/sprites/npc/cyber_demon/death/0.png", "resources/sprites/npc/cyber_demon/death/1.png", "resources/sprites/npc/cyber_demon/death/2.png", "resources/sprites/npc/cyber_demon/death/3.png", "resources/sprites/npc/cyber_demon/death/4.png", "resources/sprites/npc/cyber_demon/death/5.png", "resources/sprites/npc/cyber_demon/death/6.png", "resources/sprites/npc/cyber_demon/death/7.png", "resources/sprites/npc/cyber_demon/death/8.png"]
CYBER_IDLE = ["resources/sprites/npc/cyber_demon/idle/0.png", "resources/sprites/npc/cyber_demon/idle/1.png", "resources/sprites/npc/cyber_demon/idle/2.png", "resources/sprites/npc/cyber_demon/idle/3.png", "resources/sprites/npc/cyber_demon/idle/4.png", "resources/sprites/npc/cyber_demon/idle/5.png", "resources/sprites/npc/cyber_demon/idle/6.png", "resources/sprites/npc/cyber_demon/idle/7.png"]
CYBER_PAIN = ["resources/sprites/npc/cyber_demon/pain/0.png", "resources/sprites/npc/cyber_demon/pain/1.png"]
CYBER_WALK = ["resources/sprites/npc/cyber_demon/walk/0.png", "resources/sprites/npc/cyber_demon/walk/1.png", "resources/sprites/npc/cyber_demon/walk/2.png", "resources/sprites/npc/cyber_demon/walk/3.png"]
CYBER_DEFAULT = ["resources/sprites/npc/cyber_demon/0.png"]

SOLDIER_ATTACK = ["resources/sprites/npc/soldier/attack/0.png", "resources/sprites/npc/soldier/attack/1.png"]
SOLDIER_DEATH = ["resources/sprites/npc/soldier/death/0.png", "resources/sprites/npc/soldier/death/1.png", "resources/sprites/npc/soldier/death/2.png", "resources/sprites/npc/soldier/death/3.png", "resources/sprites/npc/soldier/death/4.png", "resources/sprites/npc/soldier/death/5.png", "resources/sprites/npc/soldier/death/6.png", "resources/sprites/npc/soldier/death/7.png", "resources/sprites/npc/soldier/death/8.png"]
SOLDIER_IDLE = ["resources/sprites/npc/soldier/idle/0.png", "resources/sprites/npc/soldier/idle/1.png", "resources/sprites/npc/soldier/idle/2.png", "resources/sprites/npc/soldier/idle/3.png", "resources/sprites/npc/soldier/idle/4.png", "resources/sprites/npc/soldier/idle/5.png", "resources/sprites/npc/soldier/idle/6.png", "resources/sprites/npc/soldier/idle/7.png"]
SOLDIER_PAIN = ["resources/sprites/npc/soldier/pain/0.png"]
SOLDIER_WALK = ["resources/sprites/npc/soldier/walk/0.png", "resources/sprites/npc/soldier/walk/1.png", "resources/sprites/npc/soldier/walk/2.png", "resources/sprites/npc/soldier/walk/3.png"]
SOLDIER_DEFAULT = ["resources/sprites/npc/soldier/0.png"]

SHOTGUN = ["resources/sprites/weapon/shotgun/0.png", "resources/sprites/weapon/shotgun/1.png", "resources/sprites/weapon/shotgun/2.png", "resources/sprites/weapon/shotgun/3.png", "resources/sprites/weapon/shotgun/4.png", "resources/sprites/weapon/shotgun/5.png"]
DIGITS = ["resources/textures/digits/0.png", "resources/textures/digits/1.png", "resources/textures/digits/2.png", "resources/textures/digits/3.png", "resources/textures/digits/4.png", "resources/textures/digits/5.png", "resources/textures/digits/6.png", "resources/textures/digits/7.png", "resources/textures/digits/8.png", "resources/textures/digits/9.png", "resources/textures/digits/10.png"]
TEXTURES = ["resources/textures/1.png", "resources/textures/2.png", "resources/textures/3.png", "resources/textures/4.png", "resources/textures/5.png", "resources/textures/blood_screen.png", "resources/textures/game_over.png", "resources/textures/sky.png", "resources/textures/win.png"]

DATA_FILES = ["map.py", "npc.py", "obj_handler.py", "obj_renderer.py", "pathfinding.py", "player.py", "raycasting.py", "settings.py", "sound.py", "sprite_obj.py", "weapon.py"]
OPTIONS = {}

setup(
    app=["main.py"],
    data_files=DATA_FILES,
    options=dict(py2app = dict(resources=[("resources/sound/", SOUND), 
                                          ("resources/sprites/animated_sprites/green_light/", GREEN_LIGHT), 
                                          ("resources/sprites/animated_sprites/red_light/", RED_LIGHT), 

                                          ("resources/sprites/npc/caco_demon/attack/", CACO_ATTACK), 
                                          ("resources/sprites/npc/caco_demon/death/", CACO_DEATH), 
                                          ("resources/sprites/npc/caco_demon/idle/", CACO_IDLE), 
                                          ("resources/sprites/npc/caco_demon/pain/", CACO_PAIN), 
                                          ("resources/sprites/npc/caco_demon/walk", CACO_WALK), 
                                          ("resources/sprites/npc/caco_demon/", CACO_DEFAULT), 
                                          
                                          ("resources/sprites/npc/cyber_demon/attack/", CYBER_ATTACK), 
                                          ("resources/sprites/npc/cyber_demon/death/", CYBER_DEATH), 
                                          ("resources/sprites/npc/cyber_demon/idle/", CYBER_IDLE), 
                                          ("resources/sprites/npc/cyber_demon/pain/", CYBER_PAIN), 
                                          ("resources/sprites/npc/cyber_demon/walk/", CYBER_WALK), 
                                          ("resources/sprites/npc/cyber_demon/", CYBER_DEFAULT), 
                                          
                                          ("resources/sprites/npc/soldier/attack/", SOLDIER_ATTACK), 
                                          ("resources/sprites/npc/soldier/death/", SOLDIER_DEATH), 
                                          ("resources/sprites/npc/soldier/idle/", SOLDIER_IDLE), 
                                          ("resources/sprites/npc/soldier/pain/", SOLDIER_PAIN), 
                                          ("resources/sprites/npc/soldier/walk/", SOLDIER_WALK), 
                                          ("resources/sprites/npc/soldier/", SOLDIER_DEFAULT), 
                                          
                                          ("resources/sprites/weapon/shotgun/", SHOTGUN), 
                                          ("resources/textures/digits/", DIGITS), 
                                          ("resources/textures/", TEXTURES)])),
    setup_requires=['py2app']
)
